jwt implementation, log4j2 and code refactoring
WeekendDevelopment/wd-webapp-be pull request #23
Opened 2022-11-24 20:38 UTC by nithin554

Big Changes!!! Please review carefully....

- Request and Response structure changes ( for login and signup endpoints )
- JWT Implementation
- Added log4j2 logger
- Code Refactoring
- Minor Bug Fixes

2022-11-25 16:17 UTC, nithin554 commented
@pallasaisrujan @saikrishna-dev review fast

2022-11-28 10:14 UTC, saikrishna-dev requested changes

2022-11-28 10:14 UTC, saikrishna-dev commented on src/main/java/com/backend/webapp/controller/LoginController.java
> +                        .equalsIgnoreCase(EncryptionUtil.decryptData(secretManagerTemplate, user.getPasswordHash()))) {
remove `equalsIgnoreCase `while validating the password after decrypting ?

2022-11-28 10:14 UTC, saikrishna-dev commented on src/main/java/com/backend/webapp/mapper/RequestMapper.java
> +        user.setFullName(signupRequest.getFullName());
`getFullName()` Where is this defined??

2022-11-28 10:14 UTC, saikrishna-dev commented on src/main/java/com/backend/webapp/mapper/RequestMapper.java
> +        user.setFullName(signupRequest.getFullName());
same with `setFullName`

2022-11-29 07:15 UTC, nithin554 commented on src/main/java/com/backend/webapp/controller/LoginController.java
> +                        .equalsIgnoreCase(EncryptionUtil.decryptData(secretManagerTemplate, user.getPasswordHash()))) {
I will remove this

2022-11-29 07:16 UTC, nithin554 commented on src/main/java/com/backend/webapp/mapper/RequestMapper.java
> +        user.setFullName(signupRequest.getFullName());
check parent class

2022-11-29 09:33 UTC, nithin554 commented on src/main/java/com/backend/webapp/controller/LoginController.java
> +                        .equalsIgnoreCase(EncryptionUtil.decryptData(secretManagerTemplate, user.getPasswordHash()))) {
resolved

2022-11-29 09:34 UTC, saikrishna-dev approved these changes

2022-11-29 09:38 UTC, merged